spring:

  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true
  # Spring JPA
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  h2.console.enabled: true
  jpa:
    database: H2
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: create-drop
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
    logging.requests: all
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${realm}/protocol/openid-connect/certs
      client:
        provider:
          server-to-server:
            token-uri: ${keycloak.auth-server-url}/realms/${realm}/protocol/openid-connect/token
        registration:
          server-to-server:
            client-id: NO_VALUE
            client-secret: NO_VALUE
            authorization-grant-type: NO_VALUE
    logging:
      requests: changing

# Define the local keycloak realm here
realm: ISI
keycloak:
  auth-server-url: https://ssodev.muenchen.de/auth

io:
  muenchendigital:
    digiwf:
      s3:
        client:
          document-storage-url: localhost:8080
          file-expiration-time: 5 #minutes
