spring:
  application.name: @project.artifactId@
  banner.location: banner.txt
  elasticsearch:
    uris: ${spring.jpa.properties.hibernate.search.backend.hosts}
    username: ${spring.jpa.properties.hibernate.search.backend.username}
    password: ${spring.jpa.properties.hibernate.search.backend.password}
    connection-timeout: 10s
    socket-timeout: 60s

server:
  shutdown: "graceful"
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

# Config for spring actuator endpoints
management:
  server.port: ${server.port}
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true

info.application.name: @project.artifactId@
info.application.version: @project.version@
info.application.commitHash: ${buildNumber}

file:
  number.max: 50
  size.max: 52428800 # Bytes = 50 Mebibyte (MiB)
  mimetypes.allowed: application/octet-stream,application/x-dbf,text/plain,application/pdf,application/vnd.ms-outlook,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.presentation,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.presentationml.presentation,text/csv,message/rfc822,image/jpeg,image/png,image/svg+xml

stammdaten:
  csv-locations:
    import-files: true
    sobon-orientierungswerte-sozialinfrastruktur: >
      csv/SoBoNOrientierungswerteSozialeInfrastruktur2014.csv,
      csv/SoBoNOrientierungswerteSozialeInfrastruktur2017.csv,
      csv/SoBoNOrientierungswerteSozialeInfrastruktur2022.csv,
      csv/SoBoNOrientierungswerteSozialeInfrastruktur2024.csv,
      csv/SoBoNOrientierungswerteSozialeInfrastruktur2024_34.csv
    staedtebauliche-orientierungswerte: >
      csv/StaedteBaulicheOrientierungswerte2014.csv,
      csv/StaedteBaulicheOrientierungswerte2017.csv,
      csv/StaedteBaulicheOrientierungswerte2022.csv,
      csv/StaedteBaulicheOrientierungswerte2024.csv

work-assignment-information:
  message:
    freigabe:
      text: "Die Abfrage wurde freigegeben und liegt zur Bearbeitung vor.\n\nAbfrage: "
      subject: "ISI - Abfrage freigegeben - Abfrage: "
    erneute-bearbeitung:
      text: "Die Abfrage wurde an die Sachbearbeitung zurückgesendet und liegt zur Bearbeitung vor.\n\nAbfrage: "
      subject: "ISI - Abfrage an Sachbearbeitung zurückgesendet - Abfrage: "
    verschicken-der-stellungnahme:
      text: "Die Abfrage wurde weitergeleitet und liegt zur Bearbeitung vor.\n\nAbfrage: "
      subject: "ISI - Abfrage weitergeleitet - Abfrage: "
    bedarfsmeldung-erfolgte:
      text: "Die Bedarfsmeldung der Abfrage ist erfolgt und liegt zur Bearbeitung vor.\n\nAbfrage: "
      subject: "ISI - Bedarfsmeldung erfolgt - Abfrage: "
    speichern-von-sozialinfrastruktur-versorgung:
      text: "Die Abfrage ist abgeschlossen.\n\nAbfrage: "
      subject: "ISI - Abfrage abgeschlossen. - Abfrage: "

refarch:
  s3:
    client:
      enable-security: true

# siehe: https://github.com/it-at-m/refarch/tree/main/refarch-integrations/refarch-s3-integration


