package de.muenchen.isi.domain.exception;

public class AutoGeneratedFieldSetException extends Exception {

    public AutoGeneratedFieldSetException(final String message, final Throwable cause) {
        super(message, cause);
    }

    public AutoGeneratedFieldSetException(final String message) {
        super(message);
    }
}
