package de.muenchen.isi.domain.service.filter;

import de.muenchen.isi.domain.exception.AutoGeneratedFieldSetException;
import de.muenchen.isi.domain.exception.EntityNotFoundException;
import de.muenchen.isi.domain.exception.MaxCreationsReachedException;
import de.muenchen.isi.domain.exception.NotOwnerException;
import de.muenchen.isi.domain.exception.OptimisticLockingException;
import de.muenchen.isi.domain.exception.UserRoleNotAllowedException;
import de.muenchen.isi.domain.mapper.PersonalFilterDomainMapper;
import de.muenchen.isi.domain.model.filter.PersonalFilterRequestModel;
import de.muenchen.isi.domain.model.filter.PersonalFilterResponseModel;
import de.muenchen.isi.infrastructure.entity.filter.PersonalFilter;
import de.muenchen.isi.infrastructure.repository.filter.PersonalFilterRepository;
import de.muenchen.isi.security.AuthenticationUtils;
import java.util.List;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.PropertyValueException;
import org.springframework.orm.ObjectOptimisticLockingFailureException;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class PersonalFilterService {

    private static final int MAX_PERSONAL_FILTERS = 10;

    private final PersonalFilterDomainMapper personalFilterDomainMapper;

    private final AuthenticationUtils authenticationUtils;

    private final PersonalFilterRepository personalFilterRepository;

    /**
     * Gibt alle eigenen persönlichen Filter zurück.
     *
     * @return alle von diesem Nutzer existierenden persönlichen Filter als Liste (exklusive der userID)
     * @throws UserRoleNotAllowedException falls der Nutzer den Fallback-Sub aus AuthenticationUtils zugewiesen hat
     */
    public List<PersonalFilterResponseModel> getPersonalFilters() throws UserRoleNotAllowedException {
        var entities = personalFilterRepository.findByPersonalIDOrderByLastModifiedDateTimeDesc(
            getSubFromAuthenticatedUser()
        );
        return personalFilterDomainMapper.entities2Models(entities);
    }

    /**
     * Gibt einen spezifisch angefragten persönlichen Filter zurück.
     *
     * @param filterId des zu lesenden persönlichen Filters
     * @return den persönlichen Filter mit dieser ID (exklusive der userID)
     * @throws EntityNotFoundException falls es keinen persönlichen Filter mit dieser ID gibt
     * @throws UserRoleNotAllowedException falls der Nutzer den Fallback-Sub aus AuthenticationUtils zugewiesen hat
     * @throws NotOwnerException falls der Nutzer nicht der Ersteller des Filters ist
     */
    public PersonalFilterResponseModel getByFilterID(UUID filterId)
        throws EntityNotFoundException, UserRoleNotAllowedException, NotOwnerException {
        String userSub = getSubFromAuthenticatedUser();
        PersonalFilter entity = getFilter(filterId, userSub);
        return personalFilterDomainMapper.entity2Model(entity);
    }

    /**
     * Aktualisiert einen spezifizierten persönlichen Filter.
     *
     * @param personalFilterRequestModel entspricht neuen persönlichen Filtereinstellungen, die bestehende Filtereinstellungen überschreiben sollen
     * @return den aktualisierten persönlichen Filter (exklusive der userID)
     * @throws EntityNotFoundException falls es keinen persönlichen Filter mit dieser ID gibt
     * @throws OptimisticLockingException falls es bereits eine neuere Version der Entität in der Datenbank gibt
     * @throws UserRoleNotAllowedException falls der Nutzer den Fallback-Sub aus AuthenticationUtils zugewiesen hat
     * @throws NotOwnerException falls der Nutzer nicht der Ersteller des Filters ist
     */
    public PersonalFilterResponseModel update(PersonalFilterRequestModel personalFilterRequestModel)
        throws EntityNotFoundException, OptimisticLockingException, NotOwnerException, UserRoleNotAllowedException {
        String userSub = getSubFromAuthenticatedUser();
        var entity = getFilter(personalFilterRequestModel.getId(), userSub);
        personalFilterRequestModel.setPersonalID(userSub);
        personalFilterDomainMapper.updateEntityFromModel(personalFilterRequestModel, entity);
        try {
            entity = personalFilterRepository.saveAndFlush(entity);
        } catch (final ObjectOptimisticLockingFailureException exception) {
            final var message = "Die Daten wurden in der Zwischenzeit geändert. Bitte laden Sie die Seite neu!";
            throw new OptimisticLockingException(message, exception);
        }
        return personalFilterDomainMapper.entity2Model(entity);
    }

    /**
     * Diese Methode speichert ein {@link PersonalFilterRequestModel}.
     *
     * @param personalFilterRequestModel entspricht dem persönlichen Filter, der gespeichert werden soll
     * @return das gespeicherte {@link PersonalFilterResponseModel}.
     * @throws OptimisticLockingException falls es bereits eine neuere Version der Entität in der Datenbank gibt
     * @throws UserRoleNotAllowedException falls der Nutzer den Fallback-Sub aus AuthenticationUtils zugewiesen hat
     * @throws MaxCreationsReachedException falls der Nutzer bereits die maximale Anzahl an Filter erstellt hat
     */
    public PersonalFilterResponseModel save(PersonalFilterRequestModel personalFilterRequestModel)
        throws OptimisticLockingException, UserRoleNotAllowedException, MaxCreationsReachedException, AutoGeneratedFieldSetException {
        personalFilterRequestModel.setPersonalID(getSubFromAuthenticatedUser());
        long filterCount = personalFilterRepository.countByPersonalID(personalFilterRequestModel.getPersonalID());
        if (filterCount >= MAX_PERSONAL_FILTERS) {
            throw new MaxCreationsReachedException(
                "Maximale Anzahl an persönlichen Filtern erreicht (" + MAX_PERSONAL_FILTERS + ")."
            );
        }
        if (personalFilterRequestModel.getId() != null) {
            personalFilterRequestModel.setId(null);
        }
        var entity = personalFilterDomainMapper.model2Entity(personalFilterRequestModel);
        try {
            entity = this.personalFilterRepository.saveAndFlush(entity);
        } catch (final ObjectOptimisticLockingFailureException exception) {
            final var message = "Die Daten wurden in der Zwischenzeit geändert. Bitte laden Sie die Seite neu!";
            throw new OptimisticLockingException(message, exception);
        }
        return personalFilterDomainMapper.entity2Model(entity);
    }

    /**
     * Löscht einen spezifisch angegebenen Filter.
     *
     * @param filterId des zu löschenden persönlichen Filters
     * @throws EntityNotFoundException falls es keinen persönlichen Filter mit dieser ID gibt
     * @throws UserRoleNotAllowedException falls der Nutzer den Fallback-Sub aus AuthenticationUtils zugewiesen hat
     * @throws NotOwnerException falls der Nutzer nicht der Ersteller des Filters ist
     */
    public void delete(UUID filterId) throws EntityNotFoundException, UserRoleNotAllowedException, NotOwnerException {
        String userSub = getSubFromAuthenticatedUser();
        getFilter(filterId, userSub);
        this.personalFilterRepository.deleteById(filterId);
    }

    /**
     * @param filterId des zu lesenden persönlichen Filters
     * @param userSub des anfragenden Benutzers
     * @return die gefundene {@link PersonalFilter}-Entität sofern keine Exception geworfen wurde
     * @throws NotOwnerException falls der Nutzer nicht der Ersteller des Filters ist
     * @throws EntityNotFoundException falls es keinen persönlichen Filter mit dieser ID gibt
     */
    private PersonalFilter getFilter(UUID filterId, String userSub) throws NotOwnerException, EntityNotFoundException {
        var entity = personalFilterRepository.findByIdAndPersonalID(filterId, userSub);
        if (entity == null) {
            if (personalFilterRepository.findById(filterId).isPresent()) {
                throw new NotOwnerException("Sie sind nicht der Ersteller dieses persönlichen Filters.");
            }
            throw new EntityNotFoundException("PersonalFilter nicht gefunden.");
        }
        return entity;
    }

    /**
     * Gibt den userSub zurück sofern es kein Fallback-Wert ist.
     *
     * @return den userSub aus authenticationUtils
     * @throws UserRoleNotAllowedException falls der Nutzer den Fallback-Sub aus AuthenticationUtils zugewiesen hat
     */
    private String getSubFromAuthenticatedUser() throws UserRoleNotAllowedException {
        final String userSub = authenticationUtils.getUserSub();
        if (authenticationUtils.isSubFromUnauthenticatedUser(userSub)) {
            throw new UserRoleNotAllowedException(
                "Sie müssen authentifiziert sein, um mit persönlichen Filtern interagieren zu können"
            );
        }
        return userSub;
    }
}
