package de.muenchen.isi.infrastructure.entity.enums.lookup;

public enum StatusAbfrageEvents {

    FREIGABE,
    ZUSAETZLICHE_ABFRAGEVARIANTE,
    KEINE_ZUSAEZTLICHE_ABFRAGEVARIANTE,
    SPEICHERN_DER_VARIANTEN,

    VERSCHICKEN_DER_STELLUNGNAHME,

    BEDARFSMELDUNG_ERFOLGTE,

    SPEICHERN_VON_SOZIALINFRASTRUKTUR_VERSORGUNG,

    KEINE_BEARBEITUNG_NÖTIG,

    WEITERE_ABFRAVARIANTEN_ANLEGEN,

    ANGABEN_ANPASSEN,
    ABBRECHEN

}
