name: it@M Default Policy

codescanning:
  level: error

# Dependency Security Alerts
dependabot:
  level: high

# Dependency Licensing Alerts
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*
      - Other

  warnings:
    # Warning is the dependency isn't known
    ids:
#      - Other
      - NA

  ignores:
    ids:
      - npm://load-script@1.0.0
      - npm://slash@1.0.0
      - maven/org.jacoco:jacoco-maven-plugin
      - GPL-2.0-or-later

secretscanning:
  level: all