name: it@M Default Policy

codescanning:
  level: error

# Dependency Security Alerts
dependabot:
  level: high

# Dependency Licensing Alerts
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

  warnings:
    # Warning is the dependency isn't known
    ids:
      - Other
      - NA

  ignores:
    names:
      - pkg:npm/load-script@1.0.0
      - npm/slash@1.0.0
      - slash@1.0.0
      - slash*
    ids:
      - GPL-2.0-or-later

secretscanning:
  level: all
